services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: rootpostgress           # Usuário do PostgreSQL
      POSTGRES_PASSWORD: 1234    # Senha do PostgreSQL
      POSTGRES_DB: pedidos                # Nome do banco de dados
    ports:
      - "5432:5432"                      # Porta para acesso ao PostgreSQL

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootmongo   # Usuário do MongoDB
      MONGO_INITDB_ROOT_PASSWORD: 1234   # Senha do MongoDB
    ports:
      - "27017:27017"                         # Porta para acesso ao MongoDB

  redis:
    image: redis:6.2
    container_name: redis
    command: ["redis-server", "--requirepass", "1234"]   # Configuração de senha para o Redis
    ports:
      - "6379:6379"                           # Porta para acesso ao Redis

#docker-compose up -d
#docker-compose down

#executar arquivo docker-compose específico
#docker-compose -f docker-compose-db.yml up -d

#executar vários arquivos docker-compose
#docker-compose -f docker-compose-postgres.yml -f docker-compose-redis.yml up -d

#Remover container de arquivos docker-compose espefícificos  
#docker-compose -f nome-do-arquivo.yml down


#mongosh "mongodb://rootmongo:1234@localhost:27017/pedidos"

#Docker mongodb
# mongo --host localhost --port 27017 -u rootmongo -p 1234 --authenticationDatabase admin