server:
  port: 8082
  servlet:
    context-path: /consulta-pedido-service

spring:
  #main:
    #web-application-type: reactive
    #allow-bean-definition-overriding: true
  application:
    name: consulta-pedido-service
  cloud:
    inetutils:
      ignored-interfaces: "docker0,veth.*"
      preferred-networks: 127.0.0.1

  data:
    mongodb:
      uri: mongodb://rootmongo:1234@localhost:27017/pedidos?authSource=admin

  #redis:
    #host: localhost
    #port: 6379
    #password: 1234

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
    redis.clients.jedis: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

redis-host: localhost
redis-port: 6379
redis-password: 1234